### ISSUE TITLE
Update docs to cover ResponseStatusCodeOnNoContext

### ISSUE THREAD

**Issue by jajik** [modcluster/docs.modcluster.io#170]
See https://github.com/modcluster/mod_proxy_cluster/pull/173

**Comment by rhusar** [comment]
Ah, looks like we missed this. Going forward, we need to make sure we require documentation PRs to be created and link along code changes. 

I ll see at updating https://github.com/modcluster/mod_cluster/blob/main/.github/PULL_REQUEST_TEMPLATE.md to include that information

**Comment by jajik** [comment]
I'll try to find out if there is some cross-repo automation that we could use here.

**Comment by rhusar** [comment]
> I'll try to find out if there is some cross-repo automation that we could use here.

In other repos we are using custom bots. But that's a bit of an overkill for this org.

**Comment by rhusar** [comment]
Done.
