### ISSUE TITLE
Default values unresolved for Maxcontext, Maxnode and Maxhost attributes.

### ISSUE THREAD

**Issue by abhishekshah67** [modcluster/docs.modcluster.io#28]
I can see script tags in Defaults for  Maxcontext, Maxnode and Maxhost attributes.

> 4.5.3. Maxcontext
> 
> The maximum number of application contexts supported by mod_cluster. (Context: server config)
> 
> Default: <script src="http://gist-it.appspot.com/github/modcluster/mod_cluster/blob/master/native/mod_manager/mod_manager.c?slice=55:56&footer=minimal"></script>

The url in the script is fails with 404. 
> Unable to fetch "https://github.com/modcluster/mod_cluster/raw/master/native/mod_manager/mod_manager.c": (404)

**Comment by rhusar** [comment]
Should be fixed now, thanks.

**Comment by abhishekshah67** [comment]
The Default values are blank. I guess the gist-it url needs to be changed or value added.

**Comment by rhusar** [comment]
Needed more fixes, should be working soon.
