### ISSUE TITLE
Your site's DNS settings are using a custom subdomain, docs.modcluster.io, that's set up as an A record

### ISSUE THREAD

**Issue by rhusar** [modcluster/docs.modcluster.io#7]
The page build completed successfully, but returned the following warning for the `gh-pages` branch:

Your site's DNS settings are using a custom subdomain, docs.modcluster.io, that's set up as an A record. We recommend you change this to a CNAME record pointing at modcluster.github.io. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by Karm** [comment]
@rhusar The registrator's web app works again so I changed that:
```
- docs.modcluster.io.    A        185.199.110.153
+ docs.modcluster.io.    CNAME    modcluster.github.io
```
 :crossed_fingers:

**Comment by rhusar** [comment]
I ll testibthe morning.

**Comment by Karm** [comment]
Works.
```
$ dig docs.modcluster.io

docs.modcluster.io.	3586	IN	CNAME	modcluster.github.io.
modcluster.github.io.	3586	IN	A	185.199.110.153
modcluster.github.io.	3586	IN	A	185.199.109.153
modcluster.github.io.	3586	IN	A	185.199.108.153
modcluster.github.io.	3586	IN	A	185.199.111.153
```
